// XFAIL: *
// RUN: mlir-translate --import-wasm %S/inputs/br.wasm | FileCheck %s

/* Source code used to create this test: 
(module
(func(export "branch_to_block")
(block $my_block
br $my_block
)
)
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



//CHECK: FAIL
