// XFAIL: *
// RUN: mlir-translate --import-wasm %S/inputs/global.wasm | FileCheck %s

/* Source code used to create this test: 
(module
(import "console" "log" (func $log (param i32)))

;; import a global variable from js
(global $from_js (import "env" "from_js") i32)

;; create a global variable
(global $from_wasm i32(i32.const 10))

(func $main
;; load both global variables onto the stack
global.get $from_js
global.get $from_wasm

i32.add ;; add up both globals
call $log ;; log the result
)
(start $main)
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



// CHECK-LABEL:   "wasm.global"() <{sym_name = "global_0", type = i32}> ({
// CHECK:           %[[VAL_0:.*]] = wasm.empty_stack
// CHECK:           %[[VAL_1:.*]] = wasm.const 10 : i32 on %[[VAL_0]]
// CHECK:           %[[VAL_2:.*]] = wasm.pop i32 from %[[VAL_1]]
// CHECK:         }) {sym_visibility = "nested"} : () -> ()

//CHECK: FAIL
