// XFAIL: *
// RUN: mlir-translate --import-wasm %S/inputs/import.wasm | FileCheck %s

/* Source code used to create this test: 
(module
  (import "console" "log" (func $log (param i32)))
  (func (export "logIt")
    i32.const 13
    call $log))
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



//CHECK: FAIL
