// RUN: mlir-translate --import-wasm %S/inputs/import.wasm | FileCheck %s

/* Source code used to create this test:
(module
(import "my_module" "foo" (func $foo (param i32)))
(import "my_module" "bar" (func $bar (param i32)))
(import "my_module" "table" (table $round 2 funcref))
(import "my_module" "mem" (memory $mymem 2))
(import "my_module" "glob" (global $globglob i32))
(import "my_other_module" "glob_mut" (global $glob_mut (mut i32)))
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK-LABEL:   "wasm.import_func"() <{importName = "foo", moduleName = "my_module", sym_name = "func_0", type = (i32) -> ()}> {sym_visibility = "nested"} : () -> ()
// CHECK:         "wasm.import_func"() <{importName = "bar", moduleName = "my_module", sym_name = "func_1", type = (i32) -> ()}> {sym_visibility = "nested"} : () -> ()
// CHECK:         "wasm.import_table"() <{importName = "table", moduleName = "my_module", sym_name = "table_0", type = !wasm<tabletype !wasm.funcref "[2:]">}> {sym_visibility = "nested"} : () -> ()
// CHECK:         "wasm.import_mem"() <{importName = "mem", limits = !wasm<limit"[2:]">, moduleName = "my_module", sym_name = "mem_0"}> {sym_visibility = "nested"} : () -> ()
// CHECK:         "wasm.import_global"() <{importName = "glob", moduleName = "my_module", sym_name = "global_0", type = i32}> {sym_visibility = "nested"} : () -> ()
// CHECK:         "wasm.import_global"() <{importName = "glob_mut", isMutable, moduleName = "my_other_module", sym_name = "global_1", type = i32}> {sym_visibility = "nested"} : () -> ()
