// XFAIL: *
// RUN: mlir-translate --import-wasm %S/inputs/load.wasm | FileCheck %s

/* Source code used to create this test: 
(module
(memory (import "js" "mem")1)
(func(export "load_from_mem")(param $ptr i32)(param $len i32)(result i32)
(local $x i32)
(local.set $x (i32.load (local.get $ptr)))
(local.get 0)
)
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



//CHECK: FAIL
