// RUN: mlir-translate --import-wasm %S/inputs/store.wasm | FileCheck %s

/* Source code used to create this test:
(module
(memory $memory 1)
(export "memory" (memory $memory))
(func(export "store_in_mem")(param $num i32)
i32.const 0
local.get $num
;; store $num at position 0
i32.store
)
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK-LABEL:   "wasm.func"() <{functionType = (i32) -> (), sym_name = "func_0", sym_visibility = "nested"}> ({
// CHECK:         ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:           %[[VAL_1:.*]] = wasm.empty_stack
// CHECK:           %[[VAL_2:.*]] = wasm.const 0 : i32 on %[[VAL_1]]
// CHECK:           %[[VAL_3:.*]] = wasm.local_get %[[VAL_0]] : i32 on %[[VAL_2]]
// CHECK:           wasm.return
// CHECK:         }) : () -> ()
// CHECK:         "wasm.memory"() <{limits = !wasm<limit"[1:]">, sym_name = "mem_0"}> {sym_visibility = "nested"} : () -> ()
// CHECK:         wasm.export @mem_0 as @memory
// CHECK:         wasm.export @func_0 as @store_in_mem
