// XFAIL: *
// RUN: mlir-translate --import-wasm %S/inputs/store.wasm | FileCheck %s

/* Source code used to create this test: 
(module
(memory $memory 1)
(export "memory" (memory $memory))
(func(export "store_in_mem")(param $num i32)
i32.const 0
local.get $num
;; store $num at position 0
i32.store
)
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



//CHECK: FAIL
