// XFAIL: *
// RUN: mlir-translate --import-wasm %S/inputs/table.wasm | FileCheck %s

/* Source code used to create this test: 
(module
  (table 2 funcref)
  (func $f1 (result i32)
    i32.const 0
  )
  (func $f2 (result i32)
    i32.const 1
  )
  (elem (i32.const 0) $f1 $f2)
  (type $return_i32 (func (result i32)))
  (func (export "callByIndex") (param $i i32) (result i32)
    local.get $i
    call_indirect (type $return_i32)
  )
)
*/

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



//CHECK: FAIL
